version: '3'
services:
  nginx:
    image: nginx:1.17-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/var/www/top-movies
    ports:
      - '80:80'
  api:
    image: ebiven/vue-cli
    volumes:
      - .:/code
    ports:
      - '3000:3000'
    command: npm run api:start
  db:
    container_name: Mongo-db
    image: mongo:4
    volumes:
      - ./db/data:/data/db
    env_file:
      - .env